### ISSUE TITLE
Efficient classical weak simulation of non-stabilizer circuits with positive, discrete Wigner representation

### ISSUE THREAD

**Issue by Fe-r-oz** [apkille/Gabs.jl#11]
## Efficient Classical Weak Simulation of Quantum Circuits with Positive Discrete Wigner Representation

_Hi, Andrew! Hope this catches your interest._

_@krastanov, pinging in case you’d like to refine or modify it as appropriate. Thank you!_

### Background
The paper *[Negative Quasi-Probability as a Resource for Quantum Computation](https://arxiv.org/pdf/1201.1256)* by Veitch et. al. presents fundamental insights into the role of the discrete Wigner representation in determining the classical simulability of quantum circuits. It demonstrates that:
- Negative Wigner representation is necessary to achieve quantum computational speed-up.
- Positive Wigner representation enables efficient classical weak simulation of quantum circuits, even for certain non-stabilizer resources. These restricted circuits can't provide exponential computational speed-up.

For systems in which the dimension is an odd power of a prime, a necessary condition for computational speed-up using Clifford unitaries is negativity of the discrete Wigner representation of the input states. The major insight from this paper is that negative discrete Wigner representation is a resource that cannot be generated by stabilizer operations alone.

### Phase Space and Quasi-Probability Representations
This paper provides several extensions to the classical simulation framework, notably generalizing the Gottesman-Knill theorem.  

- The paper provides a protocol for efficiently simulating quantum circuits with Clifford gates on inputs that have a positive Wigner representation.
   - According to Veitch et. al., _The simulation scheme deals with odd dimensional systems, makes no distinction between mixed state and pure state input, and allows the simulation of a large class of non-stabilizer states._
   - This simulation achieves linear complexity with respect to the number of input registers and extends Gottesman-Knill by allowing simulation of circuits with certain non-stabilizer resources, while only reproducing the circuit’s outcome probabilities—not the complete quantum state evolution.
- This extension is a generalization of the Gottesman-Knill theorem, showing that circuits with positive Wigner values are efficiently simulable, even when involving non-stabilizer resources. The paper extends the aforementioned theorem results in three important ways:
  - **Qudit Systems**: The protocol applies to qudit systems, beyond the traditional qubit systems.
  - **Mixed State Inputs**: Simulation is possible for circuits with mixed-state inputs, not limited to pure stabilizer states.
  - **Positive Wigner Non-Stabilizer Resources**: Certain non-stabilizer states with positive Wigner values can be simulated efficiently, broadening the class of simulable resources.

### Solution
- [ ] Discrete Wigner representation: The discrete Wigner representation of a state $\rho \in L(C_{p^n})$ is a quasi-probability distribution over $\mathbb{Z}_k \times \mathbb{Z}_k$, given by $W_r(u) = \frac{1}{d} \text{Tr}(A_u \rho)$, where $A_u$ are phase space point operators.
- [ ] Test important features of above representation:
  - [ ]  (Discrete Hudson’s theorem): positive representation if and only if pure state
  - [ ] Clifford operations preserve positive representation
  - [ ] negative representation for states that can't be classically simulated.
- [ ] Clifford Group representation over finite fields: Test $U_{F,a} T_{u} U^\dagger_{F,a} = T_{F, u+a}$ and $U_{F,a} = U_{F} T_{a}$. The matrix $F$ is a $2n \times 2n$ symplectic matrix with entries in $\mathbb{Z}_p$, and $a \in (\mathbb{Z}_p \times \mathbb{Z}_p)^n$.
- [ ] Probabilistic Algorithm Class 1: Family of Simulable Quantum Algorithms
- [ ] Probabilistic Algorithm Class 2: Classical Simulation Algorithm
- [ ] Maybe some more low-hanging fruits

### Outcome
By incorporating support for this functionality, the package would:
- Enable efficient classical weak simulation of quantum circuits with positive Wigner representation.

### Future Directions

The discrete Wigner function explored in this paper draws a close analogy to the continuous-variable Wigner function. In the continuous setting, a pure state exhibits a [positive Wigner representation](https://arxiv.org/abs/quant-ph/0702004) if and only if it is Gaussian, and "_a unitary evolution acts as a symplectic flow on the phase space if and only if_" it corresponds to a quadratic Hamiltonian. Notably, [Brocker and Werner's findings](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.71.022316) reveal that certain mixed states, despite not being representable as probabilistic mixtures of Gaussian states, can still possess a positive Wigner function.

In addition, [recent studies](https://arxiv.org/pdf/1210.1783) suggest that efficient classical simulation may be achievable for continuous-variable systems with non-Gaussian mixed states under quadratic Hamiltonian dynamics, provided these states have a positive Wigner representation. This implies that the efficient weak simulation approach established by Veitch et. al. for non-stabilizer states with positive Wigner representations extend to the continuous-variable case.

**Comment by apkille** [comment]
Hi @Fe-r-oz , thanks for the interest! I think the [last paper](https://arxiv.org/pdf/1210.1783) that you briefly mentioned is more relevant to this library than [the one that you summarized](https://arxiv.org/pdf/1201.1256). Gabs after all is specifically motivated to simulate phase space representations of Gaussian quantum states, rather than stabilizer states. Do you have a more concrete idea of how you would like this paper to be implemented? It's unclear to me what a solution such as "Clifford Group representation over finite fields" would exactly entail.

**Comment by apkille** [comment]
Hi @Fe-r-oz, I'm going to close this issue for now since it's gone a bit stale. If you would like to add anymore discussion to this issue, just ping me and I can open it again.

**Comment by Fe-r-oz** [comment]
Hi, Andrew,

Thanks so much for your feedback. You’re absolutely right—I should have provided concrete suggestions. Your comments made me realize that I need to refine and polish the post further, ensuring I present clear, actionable steps.

I held off from further discussion because I knew you were focused on building the package, and I didn’t want to interrupt your workflow. I realize now that it was stupid of me to propose a new enhancement while you were in the midst of development of essential features.

My plan is to revisit the paper once things settle and then propose concrete next steps. In the meantime, I should focus on addressing good first issues to better understand the current state of the package. This will help me gain deeper insights and allow me to suggest more informed, actionable steps. 

Best Regards,
